# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

platform:
  - x64
  - x86

clone_depth: 10

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

# What combinations to test
environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 5
    - nodejs_version: 4

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm install -g npm
  - npm --version
  - npm install -g gulp
  - npm install

build: off

build_script:
  - gulp init

test_script:
  - cmd: gulp build --release --ie
